[project]
name = "options-tool"
version = "0.1.0"
description = "A tool for analyzing options"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "plotly",
    "scipy",
    "yfinance",
    "streamlit"
]
